#!/usr/bin/env bash
# Full launch-pass seed chain, and the regeneration of apps/mobile/.env.maestro
# that has to follow it.
#
# WHY ONE SCRIPT
# The chain has six ordered steps and two of them used to be hand-typed psql.
# Run out of order, or with one step skipped, the result is not an error — it is
# a green run against fixtures that do not exist. `seed-e2e-approval-fixtures.ts`
# in particular prints `[skip]` and exits 0 when "Our household" is missing, so
# this script greps for that and fails loudly.
#
# A full `supabase db reset` invalidates every id in .env.maestro, so the file
# is rewritten from the seeders' own `# --- eval me` output rather than
# hand-merged. Ids from a prior reset are dead; never merge an old copy.
#
# Usage:
#   scripts/seed-launch-pass.sh            # full: db reset + whole chain
#   scripts/seed-launch-pass.sh --no-reset # re-seed fixtures, keep the DB
set -euo pipefail
cd "$(dirname "$0")/.."

eval "$(supabase status -o env | sed 's/^/export /')"
case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *) echo "refusing: local stack reported $API_URL" >&2; exit 1 ;;
esac
export SUPABASE_URL="$API_URL"
export SUPABASE_ANON_KEY="$ANON_KEY"
export SUPABASE_SERVICE_KEY="$SERVICE_ROLE_KEY"

OUT=$(mktemp -t launchpass-seed)
trap 'rm -f "$OUT"' EXIT

step() { echo; echo "==> $*"; }

# `[skip]` from a fixture seeder is a silent no-op that exits 0. Treat it as
# fatal: downstream flows would fail on missing fixtures and read as app bugs.
run_seed() {
  local label="$1"; shift
  step "$label"
  "$@" 2>&1 | tee "$OUT"
  if grep -q '^\[skip\] *Could not find' "$OUT"; then
    echo "FATAL: $label skipped its work — the household it needs does not exist." >&2
    exit 1
  fi
}

if [ "${1:-}" != "--no-reset" ]; then
  step "supabase db reset (destructive) + migrations + test users"
  scripts/dev-local.sh reset
else
  step "skipping db reset (--no-reset)"
fi

run_seed "bootstrap: Our household + nanny draft household" \
  bun run scripts/seed-launch-pass-bootstrap.ts
BOOTSTRAP_KV=$(sed -n '/^# --- eval me/,$p' "$OUT" | grep -E '^[A-Z0-9_]+=' || true)

run_seed "seed-e2e-approval-fixtures (--reset)" \
  bun run scripts/seed-e2e-approval-fixtures.ts --reset
# This one prints `KEY: value`, not KEY=VALUE — convert the three ids by hand.
APPROVAL_KV=$(grep -E '^ *(EXTRA_SHIFT_ID|DEMOTED_SHIFT_ID|TIME_ENTRY_ID): ' "$OUT" \
  | sed -E 's/^ *([A-Z_]+): +([^ ]+).*/\1=\2/' || true)

run_seed "seed-second-household (LEAKCANARY)" \
  bun run scripts/seed-second-household.ts
# That seeder prints canary strings but no id, and flow 22 deep-links by id.
# Flows address carers by user id in a testID (pay-carer-picker-<id>), so the
# ids of the cast members no seeder prints are needed too.
NANNY2_ID=$(psql "$DB_URL" -tAc "select id from auth.users where email='nanny2@steadilynanny.test'" | tr -d ' ')
COPARENT_ID=$(psql "$DB_URL" -tAc "select id from auth.users where email='coparent@steadilynanny.test'" | tr -d ' ')
OTHER_PARENT_ID=$(psql "$DB_URL" -tAc "select id from auth.users where email='otherparent@steadilynanny.test'" | tr -d ' ')
: "${NANNY2_ID:?nanny2 user missing}"
LEAKCANARY_HOUSEHOLD_ID=$(psql "$DB_URL" -tAc \
  "select id from public.households where name = 'LEAKCANARY the Cole household' limit 1" | tr -d ' ')
: "${LEAKCANARY_HOUSEHOLD_ID:?second household not found after seeding}"

run_seed "seed-phase4-fixtures" \
  bun run scripts/seed-phase4-fixtures.ts
PHASE4_KV=$(sed -n '/^# --- eval me/,$p' "$OUT" | grep -E '^PHASE4_[A-Z0-9_]+=' || true)

run_seed "seed-usual-week-fixtures" \
  bun run scripts/seed-usual-week-fixtures.ts
USUALWEEK_KV=$(sed -n '/^# --- eval me/,$p' "$OUT" | grep -E '^USUAL_WEEK_[A-Z0-9_]+=' || true)

# The one value no seeder can derive: it must match apps/api/.env or the
# cover-ask-expiry curl 401s and flow 13b passes against an unexpired ask.
JOB_API_KEY=$(grep -E '^JOB_API_KEY=' apps/api/.env | cut -d= -f2- | tr -d '"'"'"'')
: "${JOB_API_KEY:?JOB_API_KEY missing from apps/api/.env}"

# The bootstrap's PHASE4_HOUSEHOLD_ID and the phase4 seeder's must agree — they
# resolve the same household by the same rule, so a mismatch means one of them
# adopted a stray. Fail rather than pick one.
BOOT_HH=$(echo "$BOOTSTRAP_KV" | grep '^PHASE4_HOUSEHOLD_ID=' | cut -d= -f2)
SEED_HH=$(echo "$PHASE4_KV"    | grep '^PHASE4_HOUSEHOLD_ID=' | cut -d= -f2)
if [ -n "$SEED_HH" ] && [ "$BOOT_HH" != "$SEED_HH" ]; then
  echo "FATAL: household id mismatch — bootstrap=$BOOT_HH phase4=$SEED_HH" >&2
  exit 1
fi

step "regenerating apps/mobile/.env.maestro"
{
  echo "# Maestro E2E credentials + fixture IDs — GENERATED by"
  echo "# scripts/seed-launch-pass.sh on $(date '+%Y-%m-%d %H:%M:%S')."
  echo "# Every id below belongs to THIS reset. Do not hand-merge an older copy:"
  echo "# ids from a prior reset are dead."
  echo
  echo "PARENT_EMAIL=parent@steadilynanny.test"
  echo "PARENT_PASSWORD=SteadilyTest!2026"
  echo
  echo "NANNY_EMAIL=nanny@steadilynanny.test"
  echo "NANNY_PASSWORD=SteadilyTest!2026"
  echo
  echo "COPARENT_EMAIL=coparent@steadilynanny.test"
  echo "COPARENT_PASSWORD=SteadilyTest!2026"
  echo "NANNY2_EMAIL=nanny2@steadilynanny.test"
  echo "NANNY2_PASSWORD=SteadilyTest!2026"
  echo "OTHER_PARENT_EMAIL=otherparent@steadilynanny.test"
  echo "LEAKCANARY_HOUSEHOLD_ID=${LEAKCANARY_HOUSEHOLD_ID}"
  echo "NANNY2_ID=${NANNY2_ID}"
  echo "COPARENT_ID=${COPARENT_ID}"
  echo "OTHER_PARENT_ID=${OTHER_PARENT_ID}"
  echo
  echo "# Must match JOB_API_KEY in apps/api/.env (jobAuth middleware)."
  echo "JOB_API_KEY=${JOB_API_KEY}"
  echo
  echo "# Monday anchor for the Hours deep-link regression (flow 05)."
  echo "HOURS_DEEPLINK_WEEK_START=2026-01-05"
  echo
  echo "# --- seed-e2e-approval-fixtures.ts (flows 02/03/04) ---"
  echo "$APPROVAL_KV"
  echo
  echo "# --- seed-launch-pass-bootstrap.ts ---"
  echo "$BOOTSTRAP_KV"
  echo
  echo "# --- seed-phase4-fixtures.ts ---"
  echo "$PHASE4_KV"
  echo
  echo "# --- seed-usual-week-fixtures.ts (flows 21/25) ---"
  echo "$USUALWEEK_KV"
  echo
  echo "PHASE4_TEST_PASSWORD=SteadilyTest!2026"
} > apps/mobile/.env.maestro

# A blank value reaches Maestro as the literal string "undefined" and turns a
# missing fixture into a mystery assertion failure three flows later.
if grep -qE '^[A-Z0-9_]+=$' apps/mobile/.env.maestro; then
  echo "FATAL: empty values in .env.maestro:" >&2
  grep -nE '^[A-Z0-9_]+=$' apps/mobile/.env.maestro >&2
  exit 1
fi

echo
echo "wrote apps/mobile/.env.maestro ($(grep -cE '^[A-Z0-9_]+=' apps/mobile/.env.maestro) keys)"
