/**
 * The nanny's OWN pay record (D-29, `docs/design/screens-pay-terms.md`
 * §12.1) — a week, a date range, or a year of her own approved weeks, gross,
 * and a YTD total. "Generated by her, from My pay, without asking anyone."
 *
 * Every figure here already exists in a frozen approved week — nothing new
 * is computed, it is assembled and handed over. Callers pass only rows built
 * from an ALREADY-EXPORTABLE week (`TimesheetQueryService`'s own
 * `not_approved`/`hours_only` refusals): this module never sees a live
 * estimate, so it has nothing to refuse itself.
 *
 * =============================================================================
 * THE CSV COLUMN CONTRACT
 * =============================================================================
 *
 * Encoding: UTF-8, no BOM. CRLF-terminated (RFC 4180 §2.1), including the
 * last record. Fields escaped per `./csv.ts`.
 *
 * 1. ONE header record: `week_start,week_end,approved_at,gross_minor,
 *    reimbursements_minor,currency`.
 * 2. ONE record per included week, in the order given (the caller sorts).
 *    `gross_minor`/`reimbursements_minor` are the week's OWN frozen figures
 *    — never recomputed, never summed here with a different currency.
 * 3. ONE empty record (the section separator), then the summary, each
 *    `key,value`:
 *    | key                     | value                                       |
 *    |-------------------------|----------------------------------------------|
 *    | carer_display_name      | quoted if it needs it                        |
 *    | household_display_name  | OMITTED ENTIRELY when the caller supplies none |
 *    | range_start / range_end | the requested range, ISO `YYYY-MM-DD`        |
 *    | weeks_included          | count of rows above — lets a reader check the sum |
 *    | ytd_gross_minor         | the EXACT sum of the rows' `gross_minor`     |
 *    | ytd_reimbursements_minor| the EXACT sum of the rows' `reimbursements_minor` |
 *    | currency                | ISO-4217 — ONE currency for the whole range; the caller refuses (never blends) a range that spans more than one |
 *
 * EVERY AMOUNT IS AN INTEGER IN MINOR UNITS — never a formatted major-unit
 * float, never a currency symbol (`docs/11-MONEY.md` §1). This module
 * computes no tax; the caller's own screen says so in prose.
 *
 * Filename: `steadily-pay-summary-<rangeStart>-to-<rangeEnd>-<carer-slug>.csv`.
 *
 * @module domains/timesheet/utils/carerPaySummaryCsv
 */
import { CSV_LINE_TERMINATOR, csvRow } from './csv';
import { carerSlug } from './weekExportCsv';

const HEADER: readonly string[] = [
  'week_start',
  'week_end',
  'approved_at',
  'gross_minor',
  'reimbursements_minor',
  'currency',
];

export interface CarerPaySummaryRow {
  weekStart: string;
  weekEnd: string;
  /** ISO-8601 UTC — every row here is an approved week, so this is never null. */
  approvedAt: string;
  grossMinor: number;
  reimbursementsMinor: number;
}

export interface CarerPaySummaryCsvInput {
  carerDisplayName: string;
  /** Optional household/payroll identifier (082, D-29) — omitted when absent. */
  householdDisplayName?: string | null;
  /** ONE currency for the whole range — see the module doc's `currency` row. */
  currency: string;
  rangeStart: string;
  rangeEnd: string;
  /** Already frozen, already exportable, already in the requested range —
   * this module trusts the caller's filtering and does no refusing itself. */
  rows: readonly CarerPaySummaryRow[];
}

export interface CarerPaySummaryCsv {
  filename: string;
  csv: string;
}

export function renderCarerPaySummaryCsv(
  input: CarerPaySummaryCsvInput
): CarerPaySummaryCsv {
  const { carerDisplayName, householdDisplayName, currency, rows } = input;

  let ytdGrossMinor = 0;
  let ytdReimbursementsMinor = 0;
  const rowRecords = rows.map(row => {
    ytdGrossMinor += row.grossMinor;
    ytdReimbursementsMinor += row.reimbursementsMinor;
    return csvRow([
      row.weekStart,
      row.weekEnd,
      row.approvedAt,
      String(row.grossMinor),
      String(row.reimbursementsMinor),
      currency,
    ]);
  });

  const records: string[] = [csvRow(HEADER), ...rowRecords, ''];
  records.push(csvRow(['carer_display_name', carerDisplayName]));
  if (householdDisplayName) {
    records.push(csvRow(['household_display_name', householdDisplayName]));
  }
  records.push(
    csvRow(['range_start', input.rangeStart]),
    csvRow(['range_end', input.rangeEnd]),
    csvRow(['weeks_included', String(rows.length)]),
    csvRow(['ytd_gross_minor', String(ytdGrossMinor)]),
    csvRow(['ytd_reimbursements_minor', String(ytdReimbursementsMinor)]),
    csvRow(['currency', currency])
  );

  return {
    filename: `steadily-pay-summary-${input.rangeStart}-to-${input.rangeEnd}-${carerSlug(carerDisplayName)}.csv`,
    csv: records.map(record => `${record}${CSV_LINE_TERMINATOR}`).join(''),
  };
}
