/**
 * @module domains/timesheet/__tests__/weekReceiptHtml.test
 *
 * The PDF receipt's HTML is built from the ALREADY-FETCHED week payload —
 * no second network call, no second money derivation. This file pins the two
 * things that can silently go wrong in a string builder: escaping (a carer
 * named `Ana & Co <3` must not become markup) and the promise that every
 * figure handed in actually reaches the document.
 */
import { describe, expect, it } from 'bun:test';
import { buildWeekReceiptHtml } from '../utils/weekReceiptHtml';

const base = {
  title: 'Weekly statement',
  carerLabel: 'Carer',
  carerName: 'Amara Okafor',
  weekLabel: 'Week',
  weekRangeLabel: '3 Aug – 9 Aug',
  lines: [
    { label: 'Hours worked', subLine: '38h 00m at £18.50', amount: '£703.00' },
    { label: 'Overtime pay', subLine: '2h 00m at £27.75', amount: '£55.50' },
  ],
  totals: [
    { label: 'Gross pay', value: '£758.50' },
    { label: 'Paid to date', value: '£500.00' },
    { label: 'Balance due', value: '£258.50' },
  ],
  footer: 'Generated by Steadily.',
};

describe('buildWeekReceiptHtml', () => {
  it('is a self-contained HTML document with inline styles only', () => {
    const html = buildWeekReceiptHtml(base);

    expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
    // printToFileAsync renders in an isolated web view with no network and,
    // on iOS, no access to local assets — an external stylesheet or image
    // would silently render as nothing.
    expect(html).not.toContain('<link');
    expect(html).not.toContain('src=');
  });

  it('carries every line and every total into the document', () => {
    const html = buildWeekReceiptHtml(base);

    expect(html).toContain('Hours worked');
    expect(html).toContain('38h 00m at £18.50');
    expect(html).toContain('£703.00');
    expect(html).toContain('Overtime pay');
    expect(html).toContain('Balance due');
    expect(html).toContain('£258.50');
    expect(html).toContain('Amara Okafor');
    expect(html).toContain('3 Aug – 9 Aug');
    expect(html).toContain('Generated by Steadily.');
  });

  it('escapes every interpolated value — a name is data, never markup', () => {
    const html = buildWeekReceiptHtml({
      ...base,
      carerName: 'Ana & Co <script>alert("x")</script>',
    });

    expect(html).not.toContain('<script>');
    expect(html).toContain('Ana &amp; Co &lt;script&gt;');
  });

  it('omits the lines block entirely when the week has no priced lines', () => {
    const html = buildWeekReceiptHtml({ ...base, lines: [] });

    expect(html).not.toContain('Hours worked');
    // The totals are still the point of the receipt, so they survive.
    expect(html).toContain('Gross pay');
  });
});
